// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHVKY-jyPS1ORgNYpPumGOMN7z7p_cw0',
    appId: '1:526192892058:web:a9210d15bc4e94a1df2723',
    messagingSenderId: '526192892058',
    projectId: 'policili',
    authDomain: 'policili.firebaseapp.com',
    storageBucket: 'policili.firebasestorage.app',
    measurementId: 'G-59QW38EZ89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg594J-ap3pRaoZS9w19QjesV0q0jZrbc',
    appId: '1:526192892058:android:47eddbba5fa8d096df2723',
    messagingSenderId: '526192892058',
    projectId: 'policili',
    storageBucket: 'policili.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCSDYbB0klkaCJEreZ16-p2JEmW38CbcQ',
    appId: '1:526192892058:ios:6287175b90677804df2723',
    messagingSenderId: '526192892058',
    projectId: 'policili',
    storageBucket: 'policili.firebasestorage.app',
    iosBundleId: 'com.example.policiliApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCSDYbB0klkaCJEreZ16-p2JEmW38CbcQ',
    appId: '1:526192892058:ios:6287175b90677804df2723',
    messagingSenderId: '526192892058',
    projectId: 'policili',
    storageBucket: 'policili.firebasestorage.app',
    iosBundleId: 'com.example.policiliApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHVKY-jyPS1ORgNYpPumGOMN7z7p_cw0',
    appId: '1:526192892058:web:f951b115b2edc733df2723',
    messagingSenderId: '526192892058',
    projectId: 'policili',
    authDomain: 'policili.firebaseapp.com',
    storageBucket: 'policili.firebasestorage.app',
    measurementId: 'G-GN2BNJ1CNP',
  );
}
